services:
  - type: web
    name: transgo
    env: php
    plan: free
    buildCommand: composer install && npm install && npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql

  - type: mysql
    name: transgo-mysql
    plan: free
    version: "8.0"